### ISSUE TITLE
 ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by harishankards** [BenvinD/Crowd-Detection-And-Analyzation#1]
I cloned and tried to run the code. But I ran into the following issue:

```
 import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

matplotlib is already installed:

Because, when I give `conda install matplotlib`, the following happens:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

```

**Comment by AdarshGDaniel** [comment]
> I cloned and tried to run the code. But I ran into the following issue:
> 
> ```
>  import matplotlib.pyplot as plt
> ModuleNotFoundError: No module named 'matplotlib'
> ```
> 
> matplotlib is already installed:
> 
> Because, when I give `conda install matplotlib`, the following happens:
> 
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> # All requested packages already installed.
> ```

**Comment by AdarshGDaniel** [comment]
Hey !
•
It seems like you have two different python installed in your system, one with all the python libraries and the other with few missing. Here are a few ways you can fix the problem:

   »Try removing the alternate python installed in your system   
   »Change the path to the libraries installed  
   »Install matplotlib from your terminal 

Hopefully these help you to fix the problem. 
•

**Comment by nikhilSolomon** [comment]
> I cloned and tried to run the code. But I ran into the following issue:
> 
> ```
>  import matplotlib.pyplot as plt
> ModuleNotFoundError: No module named 'matplotlib'
> ```
> 
> matplotlib is already installed:
> 
> Because, when I give `conda install matplotlib`, the following happens:
> 
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> # All requested packages already installed.
> ```

Try using pip install matplotlib in your terminal

**Comment by hiruthicShaSS** [comment]
> I cloned and tried to run the code. But I ran into the following issue:
> 
> ```
>  import matplotlib.pyplot as plt
> ModuleNotFoundError: No module named 'matplotlib'
> ```
> 
> matplotlib is already installed:
> 
> Because, when I give `conda install matplotlib`, the following happens:
> 
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> # All requested packages already installed.
> ```

Dude seems like you are using jupyter notebook or you might not updated.
If you can report us the version of conda, jupyter, matplotlib, and the default python

**Comment by Nancy308** [comment]
**Give a try for these three methods**

**First method:**

Simply install matplotlib using **"pip install matplotlib"** in Anaconda prompt 

                   (or)

**Second method:**

Step1: If you don't have anaconda then install Anaconda console from the official website 

Step2: After install open anaconda prompt from windows search bar and follow these steps

Step3: Install virtual environment by entering **"pip install virtualenv"** 

Step4: Create separate VM  **"py -m venv venv"**

Step5: Activate using command **"venv\Scripts\activate"**

Step6: Install **"pip install matplotlib"** 

                    (or)

**Third method**

Simply download matplotlib package from pip official website “pypi.org” and go to download page find a matching windows version and python version

![pypi](https://user-images.githubusercontent.com/58805353/71968290-9e0eb280-322a-11ea-85f2-91266b339662.png)

After that in anaconda prompt use "cd" go to the path where you download the package locally and finally install using
**"pip install package name.whl"**  

![matplotlib](https://user-images.githubusercontent.com/58805353/71968330-b252af80-322a-11ea-8ee1-ca042641c711.png)


I’m sure this will work 100% give it a try.
